controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [left_wheel_rotate, right_wheel_rotate]
    front_wheels_names: [left_wheel_hinge, right_wheel_hinge]
    base_frame_id: base_link
    enable_odom_tf: false
    use_stamped_vel: false
    front_wheel_track: 0.5
    rear_wheel_track: 0.5
    wheelbase: 0.8
    rear_wheels_radius: 0.1
    front_wheels_radius: 0.1

      

     